# Basic Information 
title: CHENWEI ZHANG
position: Ph.D. Student
affiliation: University of British Columbia
affiliation_link: https://www.cs.ubc.ca/
email: cwzhang (at) cs.ubc.ca

# Search Engine Optimization (SEO)
# The following information is used to improve the website traffic from search engines, e.g., Google.
keywords: Chenwei Zhang, chenwei zhang, chenweizhang, zhang chenwei, chwzhang, chwzhan, UBC, ubc, Chenwei Zhang ubc, University of British Columbia, 张晨伟, Chenwei Zhang CS, Chenwei Zhang UBC CS PhD, Chenwei Zhang UBC, Chenwei Zhang cryoEM, Chenwei Zhang proteins, Chenwei Zhang DNA kinetics, Chenwei Zhang UWaterloo, Chenwei Zhang UW, Chenwei Zhang Think big, Chenwei Zhang Think different, Chenwei Zhang atomic model building,  Chenwei Zhan AI4Science, Chenwei Zhang Amgen, Anne Condon, Khanh Dao Duc, Chenwei Zhan NeurIPS, Chenwei Zhang MLSB, Chenwei Zhan University of British Columbia, University of Waterloo, ViDa, Chenwei Zhang ViDa
description: Chenwei Zhang is a Ph.D student at University of British Columbia (UBC). His research lies in AI4Science, deep learning, graph embeddings, protein atomic model building, cryoEM analysis, and DNA kinetics.
canonical: https://chwzhang.com/


# Links 
# If you don't need one of them, you may delete the corresponding line.
google_scholar: https://scholar.google.com/citations?user=urFl1EUAAAAJ&hl=en&authuser=1
cv_link: assets/files/curriculum_vitae.pdf
github_link: https://github.com/chenwei-zhang
linkedin: https://www.linkedin.com/in/chenweizhang95/
twitter: https://twitter.com/ChenweiZhang

# Images (e.g., your profile picture and your website's favicon) 
# "favicon" and "favicon_dark" are used for the light and dark modes, respectively. 
avatar: ./assets/img/avatar.jpg
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png

# Footnote
# You may use the option to disable the footnote, "Powered by Jekyll and Minimal Light theme."
enable_footnote: true

# Auto Dark Mode
# You may use the option to disable the automatic dark theme
auto_dark_mode: true

# Font
# You can use this option to choose between Serif or Sans Serif fonts.
font: "Serif" # or "Sans Serif"

# Google Analytics ID
# Please remove this if you don't use Google Analytics
google_analytics: G-DPP82G6KBQ

# Use this project as a remote theme for GitHub Pages
# See the guide here: https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/adding-a-theme-to-your-github-pages-site-using-jekyll
remote_theme: yaoyao-liu/minimal-light

# The following files will be removed from the generated website.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - README_zh_Hans.md
  - README_zh_Hant.md
  - README_de.md
  - LICENSE
  - minimal-light.gemspec
  - html_source_file/
